version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.3.9-fpm-stretch
    steps:
      - checkout
      - run: 
          name: Installing system dependencies
          command: |
            sudo apt update
            sudo docker-php-ext-install zip pdo pdo_mysql bcmath
      - run:
          name: Installing app dependencies
          command: composer install -n --prefer-dist
      - run:
          name: Running tests
          command: ./vendor/bin/phpunit
workflows:
  version: 2
  build:
    jobs:
      - test